const PHONE_REGISTERED = "PHONE REGISTERED";
const REQUEST_REALTIMEDTB_ERROR = "REQUEST REALTIME DATABASE ERROR";
const NEXMO_SERVER_ERROR = "NEXMO SERVER ERROR";
const ADD_VERIFY_DATA_ERROR = "ADD NEW VERIFY DATA ERROR";
const ADD_VERIFY_DATA_SUCCESS = "ADD VERIFY DATA SUCCESS";
const SEND_TOKEN_SUCCESS = "SEND TOKEN SUCCESS";
const SEND_TOKEN_ERROR = "SEND TOKEN ERROR";
const ADD_USER_DATA_ERROR = "ADD USER DATA ERROR";
const ADD_USER_DATA_SUCCESS = "ADD USER DATA SUCCESS";
const REGISTER_SUCCESS = "REGISTER SUCCESS";
const VERIFY_TOKEN_ERROR = "VERIFY TOKEN ERROR";
const CANCEL_VERIFICATION_ERROR = "CANCEL PHONE VERIFICATION ERROR"
const CANCEL_VERIFICATION_SUCCESS = "CANCEL VERIFICATION SUCCESS";
const PHONE_NUMBER_NOT_SEND = "PHONE_NUMBER_NOT_SEND";
const UPDATE_VERIFY_DATA_SUCCESS = "UPDATE VERIFY DATA SUCCESS";
const UPDATE_VERIFY_DATA_ERROR = "UPDATE VERIFY DATA ERROR";
const UPDATE_USER_DATA_SUCCESS = "UPDATE USER DATA SUCCESS";
const UPDATE_USER_DATA_ERROR= "UPDATE USER DATA ERROR";
const SEND_FORGOT_PASSWORD_SUCCESS = "SEND_FORGOT_PASSWORD_SUCCESS";
const SEND_FORGOT_PASSWORD_ERROR = "SEND_FORGOT_PASSWORD_ERROR";
const EMAILPHONE_NOT_EXIST = "EMAIL PHONE NOT EXIST";
const PHONE_NOT_VERIFY = "PHONE NOT VERIFY YET";
const PHONE_NOT_EXIST = "PHONE NOT EXIST";
const SEND_FORGOT_PASSWORD_AFTER_1H = "SEND FORGOT PASSWORD AFTER 1H";

module.exports = {
  PHONE_REGISTERED,
  REQUEST_REALTIMEDTB_ERROR,
  NEXMO_SERVER_ERROR,
  ADD_VERIFY_DATA_ERROR,
  ADD_VERIFY_DATA_SUCCESS,
  SEND_TOKEN_SUCCESS,
  SEND_TOKEN_ERROR,
  ADD_USER_DATA_ERROR,
  ADD_USER_DATA_SUCCESS,
  REGISTER_SUCCESS,
  CANCEL_VERIFICATION_ERROR,
  CANCEL_VERIFICATION_SUCCESS,
  VERIFY_TOKEN_ERROR,
  UPDATE_VERIFY_DATA_SUCCESS,
  UPDATE_VERIFY_DATA_ERROR,
  UPDATE_USER_DATA_SUCCESS,
  UPDATE_USER_DATA_ERROR,
  SEND_FORGOT_PASSWORD_ERROR,
  SEND_FORGOT_PASSWORD_SUCCESS,
  EMAILPHONE_NOT_EXIST,
  PHONE_NOT_VERIFY,
  PHONE_NOT_EXIST,
  SEND_FORGOT_PASSWORD_AFTER_1H
};