const PHONE_REGISTERED = "PHONE REGISTERED";
const REQUEST_REALTIMEDTB_ERROR = "REQUEST REALTIME DATABASE ERROR";
const NEXMO_SERVER_ERROR = "NEXMO SERVER ERROR";
const ADD_VERIFY_DATA_ERROR = "ADD NEW VERIFY DATA ERROR";
const ADD_VERIFY_DATA_SUCCESS = "ADD VERIFY DATA SUCCESS";
const SEND_TOKEN_SUCCESS = "SEND TOKEN SUCCESS";
const SEND_TOKEN_ERROR = "SEND TOKEN ERROR";
const ADD_USER_DATA_ERROR = "ADD USER DATA ERROR";
const ADD_USER_DATA_SUCCESS = "ADD USER DATA SUCCESS";
const REGISTER_SUCCESS = "REGISTER SUCCESS";
const VERIFY_TOKEN_ERROR = "VERIFY TOKEN ERROR";
const CANCEL_VERIFICATION_ERROR = "CANCEL PHONE VERIFICATION ERROR"
module.exports = {
  PHONE_REGISTERED,
  REQUEST_REALTIMEDTB_ERROR,
  NEXMO_SERVER_ERROR,
  ADD_VERIFY_DATA_ERROR,
  ADD_VERIFY_DATA_SUCCESS,
  SEND_TOKEN_SUCCESS,
  SEND_TOKEN_ERROR,
  ADD_USER_DATA_ERROR,
  ADD_USER_DATA_SUCCESS,
  REGISTER_SUCCESS,
  CANCEL_VERIFICATION_ERROR
};